openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0

x-yc-apigateway:
  cors:
    origin: '*'
    methods: '*'
    allowedHeaders: '*'
servers:
- url: https://d5d5ae8bj5eo4d552mfq.apigw.yandexcloud.net
paths:
  /advice:
    get:
      x-yc-apigateway-integration:
        type: http
        url: https://api.adviceslip.com/advice